services:
    go-fmt:
        image: ghcr.io/oullin/go-fmt:v0.0.16
        working_dir: /work
        volumes:
            - .:/work
        environment:
            HOST_PROJECT_PATH: ${PWD}
        command: ['help']
