packages:
  - "core"
  - "example/app"
allowBuilds:
  ',': true
  b: true
  c: true
  d: true
  e: true
  esbuild: true
  i: true
  l: true
  n: true
  o: true
  r: true
  s: true
  t: true
  u: true
