<script setup>
import FeatureCard from "@/js/components/app/FeatureCard.vue";
import FeatureHeader from "@/js/components/app/FeatureHeader.vue";
import AppLayout from "@/js/layouts/AppLayout.vue";

const breadcrumbs = [{ title: "Features" }, { title: "Forms" }, { title: "Wayfinder" }];
</script>

<template>
  <AppLayout title="Wayfinder" :breadcrumbs="breadcrumbs">
    <div class="flex flex-1 flex-col gap-6 p-4 lg:p-6">
      <FeatureHeader
        title="Wayfinder"
        description="Wayfinder generates type-safe route helpers from your Go server routes, giving your frontend full awareness of available endpoints."
      />

      <div class="grid gap-6 lg:grid-cols-2">
        <FeatureCard
          title="Route Registration"
          description="How routes are defined on the Go server."
        >
          <div class="grid gap-3 text-sm">
            <div class="rounded-md border p-3">
              <p class="mb-2 font-medium">Go Router Setup</p>
              <pre
                class="bg-muted overflow-auto rounded p-2 text-xs leading-relaxed"
              ><code>// routes.go
r := mux.NewRouter()

r.HandleFunc("/contacts", contactsIndex).
  Methods("GET").
  Name("contacts.index")

r.HandleFunc("/contacts/{id}", contactsShow).
  Methods("GET").
  Name("contacts.show")

r.HandleFunc("/contacts", contactsStore).
  Methods("POST").
  Name("contacts.store")

r.HandleFunc("/contacts/{id}", contactsUpdate).
  Methods("PUT").
  Name("contacts.update")

r.HandleFunc("/contacts/{id}", contactsDelete).
  Methods("DELETE").
  Name("contacts.destroy")</code></pre>
            </div>
          </div>
        </FeatureCard>

        <FeatureCard
          title="Generated Route Helpers"
          description="TypeScript route helpers generated by Wayfinder."
        >
          <div class="grid gap-3 text-sm">
            <div class="rounded-md border p-3">
              <p class="mb-2 font-medium">Generated Output</p>
              <pre
                class="bg-muted overflow-auto rounded p-2 text-xs leading-relaxed"
              ><code>// lib/routes.ts (auto-generated)
export const contactRoutes = {
  index: () => ({
    url: '/contacts',
    method: 'GET',
  }),
  show: (id: string | number) => ({
    url: `/contacts/${id}`,
    method: 'GET',
  }),
  store: () => ({
    url: '/contacts',
    method: 'POST',
  }),
  update: (id: string | number) => ({
    url: `/contacts/${id}`,
    method: 'PUT',
  }),
  destroy: (id: string | number) => ({
    url: `/contacts/${id}`,
    method: 'DELETE',
  }),
}</code></pre>
            </div>
          </div>
        </FeatureCard>
      </div>

      <div class="grid gap-6 lg:grid-cols-3">
        <FeatureCard
          title="Usage in Components"
          description="How to use generated routes in Vue components."
        >
          <div class="grid gap-2 text-sm">
            <div class="rounded-md border p-3">
              <pre
                class="bg-muted overflow-auto rounded p-2 text-xs leading-relaxed"
              ><code>import { contactRoutes }
  from '@/js/lib/routes'

// In a Link
&lt;Link :href="contactRoutes
  .show(contact.id).url"&gt;
  View Contact
&lt;/Link&gt;

// In a form submission
form.post(
  contactRoutes.store().url
)</code></pre>
            </div>
          </div>
        </FeatureCard>

        <FeatureCard title="Benefits" description="Why use Wayfinder.">
          <div class="grid gap-2 text-sm">
            <div class="flex items-start gap-2 rounded-md border p-3">
              <span
                class="bg-primary text-primary-foreground flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-xs"
                >1</span
              >
              <p class="text-muted-foreground">
                <span class="font-medium text-foreground">Type Safety</span> - Route parameters are
                typed, preventing runtime errors.
              </p>
            </div>
            <div class="flex items-start gap-2 rounded-md border p-3">
              <span
                class="bg-primary text-primary-foreground flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-xs"
                >2</span
              >
              <p class="text-muted-foreground">
                <span class="font-medium text-foreground">Auto-complete</span> - IDE support with
                full route discovery.
              </p>
            </div>
            <div class="flex items-start gap-2 rounded-md border p-3">
              <span
                class="bg-primary text-primary-foreground flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-xs"
                >3</span
              >
              <p class="text-muted-foreground">
                <span class="font-medium text-foreground">Single Source</span> - Routes defined once
                in Go, used everywhere.
              </p>
            </div>
            <div class="flex items-start gap-2 rounded-md border p-3">
              <span
                class="bg-primary text-primary-foreground flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-xs"
                >4</span
              >
              <p class="text-muted-foreground">
                <span class="font-medium text-foreground">Refactor Safe</span> - Rename a route on
                the server, the frontend breaks at compile time.
              </p>
            </div>
          </div>
        </FeatureCard>

        <FeatureCard title="Generation Flow" description="How routes go from Go to TypeScript.">
          <div class="grid gap-2 text-sm">
            <div class="rounded-md border p-3">
              <p class="mb-1 font-medium">1. Define Routes</p>
              <p class="text-muted-foreground">Register named routes in your Go application.</p>
            </div>
            <div class="rounded-md border p-3">
              <p class="mb-1 font-medium">2. Run Generator</p>
              <p class="text-muted-foreground">
                Execute the Wayfinder CLI to scan your routes and generate TypeScript helpers.
              </p>
            </div>
            <div class="rounded-md border p-3">
              <p class="mb-1 font-medium">3. Import and Use</p>
              <p class="text-muted-foreground">
                Import the generated helpers in your Vue components for type-safe routing.
              </p>
            </div>
            <div class="rounded-md border p-3">
              <p class="mb-1 font-medium">4. Stay in Sync</p>
              <p class="text-muted-foreground">
                Re-run the generator whenever routes change. Consider adding it to your build
                pipeline.
              </p>
            </div>
          </div>
        </FeatureCard>
      </div>
    </div>
  </AppLayout>
</template>
