package wayfinder

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

// GenerateOptions controls the output format of generated code.
type GenerateOptions struct {
	// TypeScript enables TypeScript output with type annotations.
	TypeScript bool

	// FlatOnly generates only flat function exports.
	FlatOnly bool

	// NestedOnly generates only nested object exports.
	NestedOnly bool

	// Header is prepended to the generated file.
	Header string
}

// Generate writes TypeScript or JavaScript route definitions to w.

// GenerateFile writes generated code to the file at path.

type groupMember struct {
	key   string
	route Route
}

func Generate(reg *Registry, w io.Writer, opts GenerateOptions) error {
	routes := reg.Export()

	header := opts.Header

	if header == "" {
		header = "// Auto-generated by inertia-go wayfinder — DO NOT EDIT"
	}

	if _, err := fmt.Fprintln(w, header); err != nil {
		return err
	}

	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}

	if opts.TypeScript {
		if _, err := fmt.Fprintln(w, "type RouteResult = { url: string; method: string }"); err != nil {
			return err
		}

		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}

	if !opts.NestedOnly {
		if err := generateFlat(w, routes, opts.TypeScript); err != nil {
			return err
		}
	}

	if !opts.FlatOnly {
		if !opts.NestedOnly {
			if _, err := fmt.Fprintln(w); err != nil {
				return err
			}
		}

		if err := generateNested(w, routes, opts.TypeScript); err != nil {
			return err
		}
	}

	return nil
}

func GenerateFile(reg *Registry, path string, opts GenerateOptions) error {
	f, err := os.Create(path)

	if err != nil {
		return err
	}

	defer f.Close()

	return Generate(reg, f, opts)
}

func generateFlat(w io.Writer, routes []Route, ts bool) error {
	for _, route := range routes {
		params := route.Params()
		funcName := dotToCamel(route.Name)
		method := strings.ToLower(route.Method)

		if len(params) == 0 {
			if ts {
				fmt.Fprintf(w, "export function %s(): RouteResult {\n", funcName)
			} else {
				fmt.Fprintf(w, "export function %s() {\n", funcName)
			}

			fmt.Fprintf(w, "  return { url: '%s', method: '%s' }\n", route.Pattern, method)
			fmt.Fprintln(w, "}")
		} else {
			paramSig := buildParamSignature(params, ts)
			urlTemplate := buildURLTemplate(route.Pattern)

			if ts {
				fmt.Fprintf(w, "export function %s(%s): RouteResult {\n", funcName, paramSig)
			} else {
				fmt.Fprintf(w, "export function %s(%s) {\n", funcName, paramSig)
			}

			fmt.Fprintf(w, "  return { url: %s, method: '%s' }\n", urlTemplate, method)
			fmt.Fprintln(w, "}")
		}

		fmt.Fprintln(w)
	}

	return nil
}

func generateNested(w io.Writer, routes []Route, ts bool) error {
	groups := groupRoutes(routes)
	groupNames := make([]string, 0, len(groups))

	for name := range groups {
		groupNames = append(groupNames, name)
	}

	sort.Strings(groupNames)

	for _, groupName := range groupNames {
		members := groups[groupName]

		if ts {
			fmt.Fprintf(w, "export const %s = {\n", groupName)
		} else {
			fmt.Fprintf(w, "export const %s = {\n", groupName)
		}

		for _, m := range members {
			params := m.route.Params()
			method := strings.ToLower(m.route.Method)

			if len(params) == 0 {
				if ts {
					fmt.Fprintf(w, "  %s: (): RouteResult => ({ url: '%s', method: '%s' }),\n", m.key, m.route.Pattern, method)
				} else {
					fmt.Fprintf(w, "  %s: () => ({ url: '%s', method: '%s' }),\n", m.key, m.route.Pattern, method)
				}
			} else {
				paramSig := buildParamSignature(params, ts)
				urlTemplate := buildURLTemplate(m.route.Pattern)

				if ts {
					fmt.Fprintf(w, "  %s: (%s): RouteResult => ({ url: %s, method: '%s' }),\n", m.key, paramSig, urlTemplate, method)
				} else {
					fmt.Fprintf(w, "  %s: (%s) => ({ url: %s, method: '%s' }),\n", m.key, paramSig, urlTemplate, method)
				}
			}
		}

		if ts {
			fmt.Fprintln(w, "} as const")
		} else {
			fmt.Fprintln(w, "}")
		}

		fmt.Fprintln(w)
	}

	return nil
}

func groupRoutes(routes []Route) map[string][]groupMember {
	groups := make(map[string][]groupMember)

	for _, route := range routes {
		parts := strings.SplitN(route.Name, ".", 2)

		if len(parts) < 2 {
			// Top-level routes (no dot) go into a special group.
			groups["app"] = append(groups["app"], groupMember{
				key:   route.Name,
				route: route,
			})

			continue
		}

		groupName := parts[0]
		key := dotToCamel(parts[1])
		groups[groupName] = append(groups[groupName], groupMember{
			key:   key,
			route: route,
		})
	}

	return groups
}

// dotToCamel converts "contacts.notes.store" to "contactsNotesStore".
func dotToCamel(s string) string {
	parts := strings.Split(s, ".")

	if len(parts) <= 1 {
		return s
	}

	var b strings.Builder

	b.WriteString(parts[0])

	for _, part := range parts[1:] {
		if len(part) == 0 {
			continue
		}

		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}

	return b.String()
}

// buildParamSignature creates the function parameter signature.
func buildParamSignature(params []string, ts bool) string {
	if !ts {
		return "params"
	}

	fields := make([]string, len(params))

	for i, p := range params {
		fields[i] = p + ": string | number"
	}

	return "params: { " + strings.Join(fields, ", ") + " }"
}

// buildURLTemplate converts "/contacts/{contact}" to "`/contacts/${params.contact}`".
func buildURLTemplate(pattern string) string {
	result := paramRegex.ReplaceAllStringFunc(pattern, func(match string) string {
		name := match[1 : len(match)-1]

		return "${params." + name + "}"
	})

	return "`" + result + "`"
}
